## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [92]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head(10)

,City_ID,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
0,2,Iralaya,HN,84.20,scattered clouds,15.00,-83.23,Iglesia morava renovada
1,6,Avarua,CK,75.20,overcast clouds,-21.21,-159.78,Paradise Inn
2,7,Castro,BR,76.17,scattered clouds,-24.79,-50.01,CHACARA BAILLY
3,11,Keti Bandar,PK,82.36,scattered clouds,24.14,67.45,Haji laloo memon house
4,15,Buala,SB,81.30,light rain,-8.14,159.59,Maringe Lagoon Lodge
5,16,Faya,SA,82.40,few clouds,18.39,42.45,مقبرة ال مجمل
6,17,Bethel,US,75.20,clear sky,41.37,-73.41,Courtyard by Marriott Danbury
7,20,Muborak,UZ,81.19,clear sky,39.26,65.15,Gostinitsa Prestizh
8,23,Kununurra,AU,77.00,clear sky,-15.77,128.73,Hotel Kununurra
9,26,Cabinda,AO,77.00,broken clouds,-5.55,12.20,"Hotel Executivo , 3 estrelas"

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Weather Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the fo|rmatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]

In [4]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
                                max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [83]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 


vacation_start = vacation_df.loc[(vacation_df["City"] == "Henderson")]
vacation_end = vacation_df.loc[(vacation_df["City"] == "Clyde")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == "Dillon")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == "Saint George")]
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == "Greenwood")] 

vacation_start

,City_ID,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
136,418,Henderson,US,84.99,clear sky,36.04,-114.98,Hawthorn Suites By Wyndham Las Vegas/Henderson

In [84]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
# start = vacation_stop1[["Lat","Lng"]]
# stop1 = vacation_stop1[["Lat","Lng"]]
# stop2 = vacation_stop2[["Lat","Lng"]].to_numpy()
# stop3 = vacation_stop3[["Lat","Lng"]].to_numpy()
# end = vacation_end[["Lat","Lng"]].to_numpy()

# start = [tuple(x) for x in start.to_numpy()]
# stop1 = [tuple(x) for x in stop1.to_numpy()]
# print(len(start), start)


# start.to_numpy()
# stop1.to_numpy()
#start = vacation_start[{"Lat":[("Lat")], "Lng":[("Lng")]}]
start = vacation_start['Lat'].to_numpy()[0], vacation_start['Lng'].to_numpy()[0]
stop1 = vacation_stop1['Lat'].to_numpy()[0], vacation_stop1['Lng'].to_numpy()[0]
stop2 = vacation_stop2['Lat'].to_numpy()[0], vacation_stop2['Lng'].to_numpy()[0]
stop3 = vacation_stop3['Lat'].to_numpy()[0], vacation_stop3['Lng'].to_numpy()[0]
end = vacation_end['Lat'].to_numpy()[0], vacation_end['Lng'].to_numpy()[0]

In [85]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
import gmaps.datasets

fig = gmaps.figure()
start2stop1 = gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3])
fig.add_layer(start2stop1)
fig

Figure(layout=FigureLayout(height='420px'))

In [86]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3, vacation_end],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
0,418,Henderson,US,84.99,clear sky,36.04,-114.98,Hawthorn Suites By Wyndham Las Vegas/Henderson
1,195,Dillon,US,88.00,clear sky,34.42,-79.37,Dillon Express Inn
2,151,Saint George,US,75.99,clear sky,37.10,-113.58,Best Western Plus Abbey Inn
3,688,Greenwood,US,86.00,clear sky,34.17,-82.12,Quality Inn Greenwood Hwy 25
4,600,Clyde,US,77.00,clear sky,41.30,-82.98,Red Roof Inn Clyde

In [87]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Weather Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]
max_temp = itinerary_df["Max Temp"]

In [91]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))